### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by zubair96** [shreyavshetty/AutoGenerationOfCcode#1]
i don't know to run your project in ubantu . i try to use it in flex i give error on # include y.tab.c 
header file that can't find headr file .so, i beg you to tell me how to run this project .
Thanks

**Comment by shreyavshetty** [comment]
Hi Zubair, the instructions mentioned are for Ubuntu. Please have a look at the readme mentioned under Grammer Based Approach.
Kindly reopen if issue persists.
